version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk  # Environnement Java 11 (ou 8 si nécessaire)
    steps:
      - checkout  # Récupérer le code source depuis GitHub

      - run:
          name: Maven Clean & Install
          command: mvn clean install

      - run:
          name: Run Unit Tests
          command: mvn test
