version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Environnement Java 8
    steps:
      - checkout  # Récupère le code source
      - run:
          name: Install Maven
          command: apt-get update && apt-get install -y maven
      - run:
          name: Run Unit Tests
          command: mvn test  # Exécute les tests unitaires avec Maven

workflows:
  version: 2
  build_and_testt:
    jobs:
      - build:
          filters:
            branches:
              only: master  # Branche master uniquement
