version: 2.1

# Import de l'orb Codecov pour uploader la couverture
orbs:
  codecov: codecov/codecov@3.2.4

# Définition des jobs
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout

      # Calcul du cache Maven pour éviter les téléchargements répétés
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY

      # Restauration du cache Maven
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}

      # Compilation, exécution des tests et génération du rapport de couverture
      - run:
          name: Run Tests with Maven
          command: mvn clean verify

      # Stockage des résultats de tests
      - store_test_results:
          path: target/surefire-reports

      # Sauvegarde du cache Maven
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

      # Uploader la couverture JaCoCo vers Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          flags: java-tests

# Définition du workflow
workflows:
  build-and-upload-coverage:
    jobs:
      - test-java
