version: 2.1

orbs:
  codecov: codecov/codecov@3  # Importer l'orb de Codecov

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0  # Utiliser l'image OpenJDK 17
    steps:
      - checkout  # Récupérer le code source depuis GitHub

      - restore_cache:
          key: cache-{{ checksum "pom.xml" }}

      # Compilation et génération des rapports JaCoCo
      - run:
          name: Run Maven Tests with Coverage
          command: mvn clean verify

      # Sauvegarde des résultats de test
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/site/jacoco
          destination: jacoco-report

      - save_cache:
          key: cache-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository

      # Publier le rapport JaCoCo sur Codecov
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml  # Fichier XML généré par JaCoCo
          token: $CODECOV_TOKEN  # Déclarer la variable d'environnement dans CircleCI

workflows:
  build-and-test:
    jobs:
      - test-java
